/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface AuthenticationOauthData {
	actorId: string;
	/**
	 * Linked accounts
	 */
	oauth: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type AuthenticationOauthContractDefinition =
	ContractDefinition<AuthenticationOauthData>;

export type AuthenticationOauthContract = Contract<AuthenticationOauthData>;
