/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface AuthenticationOauthData {
	actorId: string;
	/**
	 * Linked accounts
	 */
	oauth: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface AuthenticationOauthContractDefinition
	extends ContractDefinition<AuthenticationOauthData> {}

export interface AuthenticationOauthContract
	extends Contract<AuthenticationOauthData> {}
