/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface AuthenticationPasswordData {
	actorId: string;
	hash: string;
	[k: string]: unknown;
}

export type AuthenticationPasswordContractDefinition =
	ContractDefinition<AuthenticationPasswordData>;

export type AuthenticationPasswordContract =
	Contract<AuthenticationPasswordData>;
