/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface CardData {
	[k: string]: unknown;
}

export interface CardContractDefinition extends ContractDefinition<CardData> {}

export interface CardContract extends Contract<CardData> {}
