/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface ErrorData {
	transformer?: string;
	expectedOutputTypes?: unknown[];
	message?: string;
	code?: string;
	stdOutTail?: string;
	stdErrTail?: string;
	[k: string]: unknown;
}

export type ErrorContractDefinition = ContractDefinition<ErrorData>;

export type ErrorContract = Contract<ErrorData>;
