/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface EventData {
	timestamp: string;
	target: string;
	actor: string;
	payload?: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export interface EventContractDefinition
	extends ContractDefinition<EventData> {}

export interface EventContract extends Contract<EventData> {}
