/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface EventData {
	timestamp: string;
	target: string;
	actor: string;
	payload?: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type EventContractDefinition = ContractDefinition<EventData>;

export type EventContract = Contract<EventData>;
