/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface LinkData {
	inverseName: string;
	from: {
		id: string;
		type: string;
		slug?: string;
		[k: string]: unknown;
	};
	to: {
		id: string;
		type: string;
		slug?: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type LinkContractDefinition = ContractDefinition<LinkData>;

export type LinkContract = Contract<LinkData>;
