/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface LoopData {
	[k: string]: unknown;
}

export interface LoopContractDefinition extends ContractDefinition<LoopData> {}

export interface LoopContract extends Contract<LoopData> {}
