/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface LoopData {
	[k: string]: unknown;
}

export type LoopContractDefinition = ContractDefinition<LoopData>;

export type LoopContract = Contract<LoopData>;
