/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface RelationshipData {
	inverseName: string;
	title: string;
	inverseTitle: string;
	from: {
		type: string;
		[k: string]: unknown;
	};
	to: {
		type: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type RelationshipContractDefinition =
	ContractDefinition<RelationshipData>;

export type RelationshipContract = Contract<RelationshipData>;
