/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export interface RoleData {
	read: {
		[k: string]: unknown;
	};
	[k: string]: unknown;
}

export type RoleContractDefinition = ContractDefinition<RoleData>;

export type RoleContract = Contract<RoleData>;
