/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export type Email = ListOfEmailAddresses | SingleEmailAddress;
/**
 * @minItems 1
 */
export type ListOfEmailAddresses = string[];
export type SingleEmailAddress = string;
export type Avatar = string | null;
export type StartedAtTheCompany = string;
export type Country = string;
export type City = string;
export type Timezone = string;
export type FirstName = string;
export type LastName = string;
export type PreferredName = string;
export type Pronouns = string;
export type Birthday = string;
export type AboutMe = string;
export type AskMeAbout = string[];
export type Links = string[];

export interface UserData {
	status?: Available | DoNotDisturb | OnAnnualLeave | InAMeeting;
	email?: Email;
	avatar?: Avatar;
	roles: string[];
	/**
	 * Configuration options for your account
	 */
	profile?: {
		company?: string;
		startDate?: StartedAtTheCompany;
		title?: string;
		country?: Country;
		city?: City;
		timezone?: Timezone;
		name?: {
			first?: FirstName;
			last?: LastName;
			preffered?: PreferredName;
			pronouns?: Pronouns;
			[k: string]: unknown;
		};
		birthday?: Birthday;
		about?: {
			aboutMe?: AboutMe;
			askMeAbout?: AskMeAbout;
			externalLinks?: Links;
			[k: string]: unknown;
		};
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
export interface Available {
	title?: 'Available';
	value?: 'Available';
	[k: string]: unknown;
}
export interface DoNotDisturb {
	title?: 'Do Not Disturb';
	value?: 'DoNotDisturb';
	[k: string]: unknown;
}
export interface OnAnnualLeave {
	title?: 'On Annual Leave';
	value?: 'AnnualLeave';
	[k: string]: unknown;
}
export interface InAMeeting {
	title?: 'In a Meeting';
	value?: 'Meeting';
	[k: string]: unknown;
}

export interface UserContractDefinition extends ContractDefinition<UserData> {}

export interface UserContract extends Contract<UserData> {}
