/*
 * This file was automatically generated by 'npm run types'.
 *
 * DO NOT MODIFY IT BY HAND!
 */

// tslint:disable: array-type

import type { Contract, ContractDefinition } from '../';

export type Email = ListOfEmailAddresses | SingleEmailAddress;
/**
 * @minItems 1
 */
export type ListOfEmailAddresses = string[];
export type SingleEmailAddress = string;
export type Avatar = string | null;
export type StartedAtTheCompany = string;
export type Country = string;
export type City = string;
export type Timezone = string;
export type FirstName = string;
export type LastName = string;
export type PreferredName = string;
export type Pronouns = string;
export type Birthday = string;
export type AboutMe = string;
export type AskMeAbout = string[];
export type Links = string[];
/**
 * Command to send a message
 */
export type SendCommand = 'shift+enter' | 'ctrl+enter' | 'enter';
/**
 * Do not play a sound when displaying notifications
 */
export type DisableNotificationSound = boolean;

export interface UserData {
	status?: Available | DoNotDisturb | OnAnnualLeave | InAMeeting;
	email?: Email;
	hash: string;
	avatar?: Avatar;
	roles: string[];
	/**
	 * Linked accounts
	 */
	oauth?: {
		[k: string]: unknown;
	};
	/**
	 * Configuration options for your account
	 */
	profile?: {
		company?: string;
		startDate?: StartedAtTheCompany;
		type?: string;
		title?: string;
		country?: Country;
		city?: City;
		timezone?: Timezone;
		name?: {
			first?: FirstName;
			last?: LastName;
			preffered?: PreferredName;
			pronouns?: Pronouns;
			[k: string]: unknown;
		};
		birthday?: Birthday;
		about?: {
			aboutMe?: AboutMe;
			askMeAbout?: AskMeAbout;
			externalLinks?: Links;
			[k: string]: unknown;
		};
		/**
		 * The default view that is loaded after you login
		 */
		homeView?: string;
		/**
		 * The loop that the user is currently working on
		 */
		activeLoop?: string | null;
		sendCommand?: SendCommand;
		disableNotificationSound?: DisableNotificationSound;
		/**
		 * List of view slugs that are starred
		 */
		starredViews?: string[];
		/**
		 * A map of settings for view contracts, keyed by the view id
		 */
		viewSettings?: {
			/**
			 * This interface was referenced by `undefined`'s JSON-Schema definition
			 * via the `patternProperty` "^.*$".
			 */
			[k: string]: {
				[k: string]: unknown;
			};
		};
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
export interface Available {
	title?: 'Available';
	value?: 'Available';
	[k: string]: unknown;
}
export interface DoNotDisturb {
	title?: 'Do Not Disturb';
	value?: 'DoNotDisturb';
	[k: string]: unknown;
}
export interface OnAnnualLeave {
	title?: 'On Annual Leave';
	value?: 'AnnualLeave';
	[k: string]: unknown;
}
export interface InAMeeting {
	title?: 'In a Meeting';
	value?: 'Meeting';
	[k: string]: unknown;
}

export type UserContractDefinition = ContractDefinition<UserData>;

export type UserContract = Contract<UserData>;
