# This file is auto-synced from product-os/jellyfish-config/sync/.resinci-no-docker.yml
# and should only be edited there!

docker:
  publish: false
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/jellyfish-sut
      publish: false
      args:
        - BUILDKIT_INLINE_CACHE=1
npm:
  platforms:
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "14"
        - "16"
